### ISSUE TITLE
Login/Connection errors seen in Mavericks and Yosemite

### ISSUE THREAD

**Issue by theCampbell** [saucelabs/sauce-for-mac#36]
There appear to be a number of issues with the Sauce Mac app and using Yosemite.  Not immediately but some time after upgrading to Yosemite the app begins to fail with error messages about logging in.  Such as "Unauthorized; invalid access key or password", "Not authorized" and "the Sauce Labs servers cannot be reached".

Other machines on the same network (running earlier versions of OS X) can connect without incident as can some other machines running Yosemite that have yet to be affected by whatever is failing.  It looks as though the stored cookie is incorrect but removing the app as well as the following files does not correct the issue.

/private/var/db/receipts/com.saucelabs.scout.plist
/private/var/db/receipts/com.saucelabs.scout.bom
/Library/Preferences/com.saucelabs.scout.plist

Is there another location where preferences are stored that might need to be cleaned out?

**Comment by HendrikRunte** [comment]
Hi guys, any progress on this topic? Thanks in advance!

**Comment by joshmullikin** [comment]
How far out is the Horizon? Looks like latest version in app store and at http://saucelabs.com/downloads/Sauce-for-Mac.dmg is still 1.05 / build 119.

**Comment by Jonahss** [comment]
I'm sorry to report that Sauce labs has decided to officially stop supporting the Sauce for Mac app. I'm updating the readme with our reasoning now.

You're free to fork this repo, and build the app yourself. We will still merge pull requests (or add a link to a supported fork if you create one).
